project_id = "hzatoqpmnlxrsxjwtwfq"

[functions.notify-new-message]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.notify-new-shipment]
verify_jwt = false

[functions.notify-match-proposal]
verify_jwt = false

[functions.notify-match-accepted]
verify_jwt = false
